### ISSUE TITLE
Issue with hdf backend when running nested sampling.

### ISSUE THREAD

**Issue by pjs902** [nmdickson/GCfit#145]
When attempting to run a fit using nested sampling either on my laptop or under the specific setup I use on CC the following error occurs:

```python
Traceback (most recent call last):
  File "/home/pjs902/.local/bin/GCfitter", line 307, in <module>
    fit_func(**vars(args))
  File "/home/pjs902/.local/lib/python3.9/site-packages/fitter/core/main.py", line 906, in nested_fit
    backend.update_intial_batch(results)
  File "/home/pjs902/.local/lib/python3.9/site-packages/fitter/core/main.py", line 288, in update_intial_batch
    grp[key][-n_grow:] = val
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/intel2020/openmpi4/hdf5-mpi/1.12.1/lib/python3.9/site-packages/h5py-3.5.0-py3.9-linux-x86_64.egg/h5py/_hl/dataset.py", line 942, in __setitem__
    mspace = h5s.create_simple(selection.expand_shape(mshape))
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/MPI/intel2020/openmpi4/hdf5-mpi/1.12.1/lib/python3.9/site-packages/h5py-3.5.0-py3.9-linux-x86_64.egg/h5py/_hl/selections.py", line 264, in expand_shape
    raise TypeError("Can't broadcast %s -> %s" % (source_shape, self.array_shape))  # array shape
TypeError: Can't broadcast (13,) -> (13, 17)
```

This happens regardless of if I remove any left over backend files from previous runs. I'm running on commit f14291300c02eb206acc9b4fb5871ecb1844532d from the develop branch.

**Comment by pjs902** [comment]
[fitter_NGC0104.log](https://github.com/nmdickson/GCfit/files/9678633/fitter_NGC0104.log)
[slurm-65700139.log](https://github.com/nmdickson/GCfit/files/9678635/slurm-65700139.log)

**Comment by pjs902** [comment]
Just to update the progress here, I've narrowed this down to an issue with my data file when I include the pulsar data. Adding the extra proper motion data doesn't break anything but adding the pulsar data, even with the pulsar likelihood disabled breaks it.

**Comment by pjs902** [comment]
Ok, just to confirm what we speculated earlier, I didn't actually have the pulsar likelihood disabled like I thought I did. Just tested it with it properly disabled and it works fine. Haven't looked into it at all but now it seems more likely that a bunch of (or all of) the initial samples are failing, making the array of samples empty and causing the size mismatch when it tries to save to the backend.

**Comment by pjs902** [comment]
To once again document the progress over the past week, I'm now pretty sure this has nothing to do with anything going on inside the pulsar likelihoods themselves. I've tested with each of the pulsar likelihoods disabled and the issue still occurs. I've also had a look at dynesty and they specifically handle the case where all of the initial samples are returned as `-inf` and they give a specific error message for that case which we haven't yet reached. Additionally, I've tested forcing the pulsar likelihoods to just return 1 instead of whatever value they actually calculate. So, based on these tests I'm pretty sure the pulsar likelihoods themselves are not to blame. 

I have however found some _very very_ strange behaviour by dumping the results dictionary at the time of the crash:

```python
{'bound_iter': 0,
 'bound_orig': 0,
 'delta_logz': 1e+300,
 'eff': 0.9900990099009901,
 'h': -9.900990099009874e+297,
 'loglstar': -1e+300,
 'logvol': -0.009950330853168092,
 'logwt': -1e+300,
 'logz': -1e+300,
 'logzvar': -9.851812725908975e+295,
 'ncall': 1,
 'ustar': array([0.57146696, 0.75116869, 0.94833975, 0.35921788, 0.63676913,
       0.32263736, 0.50516653, 0.85124256, 0.31663921, 0.32336887,
       0.78167389, 0.38656441, 0.24449442, 0.63153795, 0.45676492,
       0.69988187, 0.50224247]),
 'vstar': array([12.71493837,  3.75833175, 14.2509264 ,  1.7960894 ,  2.22869194,
        0.36452747,  7.577498  ,  2.70248513,  0.06074136,  0.80101634,
        3.47601734, 38.65644097,  3.46696655]),
 'worst': 0,
 'worst_orig': 0}
```

In particular:
```python
results['vstar'].shape = (13,)
results['vstar'] = array([12.71493837,  3.75833175, 14.2509264 ,  1.7960894 ,  2.22869194,
        0.36452747,  7.577498  ,  2.70248513,  0.06074136,  0.80101634,
        3.47601734, 38.65644097,  3.46696655])
results['ustar'].shape = (17,)
results['ustar'] = array([0.57146696, 0.75116869, 0.94833975, 0.35921788, 0.63676913,
       0.32263736, 0.50516653, 0.85124256, 0.31663921, 0.32336887,
       0.78167389, 0.38656441, 0.24449442, 0.63153795, 0.45676492,
       0.69988187, 0.50224247])

```

The `ustar` and `vstar` arrays are different sizes. I'm entirely unsure what could be causing GCfit to infer 4 additional parameters when a pulsar likelihood is enabled. We do pass around a few extra things like the cluster's position and proper motion but I'm not sure how or even if they could affect the number of parameters that GCfit gives to dynesty.

**Comment by pjs902** [comment]
Final resolution here: I was using ViTables to modify the datafiles and it was apparently appending some extra metadata in the form of HDF `attrs`. This meant that when the length of the variable initials was read from the observations there were 4 extra elements stuck on the end.
