### ISSUE TITLE
Models fail to converge when run locally, but not on ComputeCanada servers

### ISSUE THREAD

**Issue by nmdickson** [nmdickson/GCfit#154]
For a little while now, models of most parameter values have failed to converge when run locally, but work fine when run on the compute canada cluster.
This is noticeable in that sampling and computing CIs using the `generate_model_CI` script work fine on the CC cluster, but not locally, and in fact I can confirm that grabbing a specific theta (from a run for NGC3201) and computing a model will function on the server, but not on my machine:

```python
>>> # theta value from chain[-100]
>>> th = array([4.69311672,  0.16985007,  9.20409296,  0.97578428,  1.61437803,
            0.47067033, 19.32266516,  2.37032233,  0.90420775,  1.53768745,
            2.09165824,  0.04718061,  4.59870286])

>>> m = fitter.Model(th, fitter.Observations('NGC3201'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nolan/Research/dev/GCfit/fitter/core/data.py", line 943, in __init__
    super().__init__(**self._limepy_kwargs)
  File "/home/nolan/Research/dev/renv/lib/python3.10/site-packages/limepy/limepy.py", line 175, in __init__
    raise ValueError(error)
ValueError: Error: rmax reached in mf iteration
```

It's very strange, but I suspect this has something to do with dependency differences somewhere.
I can confirm that the same version of `GCfit` and `ssptools` are installed on both machines.

The CC environment for each job is setup as:
```bash
# Load standard Python module
module purge
echo Loading modules
module load StdEnv/2020
module load openmpi
module load python/3.8
module load mpi4py/3.0.3
module load hdf5-mpi
module load gsl
module load scipy-stack/2022a
module load geos
echo Activating venv
source ~/venv/bin/activate
echo Installing fitter
```

I think Peter is also seeing this issue, so I don't think it's just my system, and I'm guessing it's to do with the required dependencies.

**Comment by nmdickson** [comment]
The mismatched dependency was `ssptools`. The [a77ae3c](https://github.com/nmdickson/ssptools/commit/a77ae3cacdfe00403d175f4a63f36ab1c03bfd0f) bugfix is required, but wasn't installed. The packaging in that library should be improved, and an actual release made, so this doesn't happen again.

In the meantime, I'm going to quickly update the package requirements, which have become dated.
